### ISSUE TITLE
DD3.5 Skills checkboxes not correctly aligned

### ISSUE THREAD

**Issue by Flink** [marcusatbang/charactersheets#57]
Hi!
Just discovered this project and it’s very nice. I just saw there’s a little problem with the DD3.5 sheet (I’m using barbarian + custom portrait character on my sheet): the checkboxes for skills aren’t aligned on the lines coming from the classes. You can see on the attached image.

![barbarian sheet](https://cloud.githubusercontent.com/assets/5648/11445295/5038f75a-952b-11e5-974a-2f7960dcfb50.PNG)

**Comment by marcusatbang** [comment]
Thanks. Is it just the Barbarian? What do you get for Ranger?

As you can probably tell, I recently changed how the skills work. To include various optional skills like psionics, subskills like Track, knowledge skills specific to your character, and to show translations in the right order, it writes the skills dynamically.

**Comment by Flink** [comment]
It seems that’s only the Barbarian yes :confused: I just tried the Ranger, Cleric, Fighter and Death Master, no problem with them.

**Comment by marcusatbang** [comment]
Okay, I think I have this addressed. It should be fixed next time I publish.

**Comment by Flink** [comment]
Great, thank you! :)

**Comment by Flink** [comment]
@marcusatbang do you know when will you publish a new version? I just created a new character sheet and the bug is still here.

**Comment by marcusatbang** [comment]
Soon. I've been on the verge of publishing it for months now.

Some of the changes in the latest version, even if they don't look very big, create the opportunity for a lot of things to go wrong. I've fixed a lot, but I need to be confident I'm not about to make things worse. I think there's just one more thing I need to fix before it can go.

**Comment by Flink** [comment]
Ok great! :+1:
